### ISSUE TITLE
How to install oneMKL this way?

### ISSUE THREAD

**Issue by hmenke** [oneapi-src/oneapi-ci#71]
I'm trying to install oneMKL on Windows with the script you provided, essentially by just exchanging `COMPONENTS=intel.oneapi.win.dpcpp-compiler` with `COMPONENTS=intel.oneapi.win.mkl.devel:intel.oneapi.win.tbb.devel:intel.oneapi.win.dpl`.

However, this install never finishes. The GitHub Action just times out after 6 hours. What am I doing wrong?

```yaml
name: oneMKL test

on: [ push ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      # https://github.com/oneapi-src/oneapi-ci/blob/master/scripts/install_windows.bat
      - name: Install Intel oneAPI Math Kernel Library (oneMKL)
        shell: cmd
        run: |
          @echo on
          REM SPDX-FileCopyrightText: 2022 Intel Corporation
          REM
          REM SPDX-License-Identifier: MIT
          set URL=https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/c961e083-5685-4f0b-ada5-c6cf16f561dd/w_BaseKit_p_2023.1.0.47256_offline.exe
          set COMPONENTS=intel.oneapi.win.mkl.devel:intel.oneapi.win.tbb.devel:intel.oneapi.win.dpl
          curl.exe --output %TEMP%\webimage.exe --url %URL% --retry 5 --retry-delay 5
          start /b /wait %TEMP%\webimage.exe -s -x -f webimage_extracted --log extract.log
          del %TEMP%\webimage.exe
          webimage_extracted\bootstrapper.exe -s --action install --components=%COMPONENTS% --eula=accept -p=NEED_VS2017_INTEGRATION=0 -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=.
          set installer_exit_code=%ERRORLEVEL%
          rd /s/q "webimage_extracted"
          exit /b %installer_exit_code%
```
